package remoteObject;

/**
* remoteObject/EventSystemInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/TLIN/eclipse-workspace/CORBAa2Lin/EventSystemInterface.idl
* Sunday, July 7, 2019 4:23:46 o'clock PM EDT
*/

public final class EventSystemInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public remoteObject.EventSystemInterface value = null;

  public EventSystemInterfaceHolder ()
  {
  }

  public EventSystemInterfaceHolder (remoteObject.EventSystemInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = remoteObject.EventSystemInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    remoteObject.EventSystemInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return remoteObject.EventSystemInterfaceHelper.type ();
  }

}
