package remoteObject;


/**
* remoteObject/EventSystemInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/TLIN/eclipse-workspace/CORBAa2Lin/EventSystemInterface.idl
* Sunday, July 7, 2019 4:23:46 o'clock PM EDT
*/

public interface EventSystemInterfaceOperations 
{

  /* manager Operations */
  boolean addEvent (String managerId, String eventId, String eventtype, int capacity);
  boolean removeEvent (String managerId, String eventId, String eventtype);
  org.omg.CORBA.Any listEventAvailability (String managerId, String eventtype);

  /* Customer Operations */
  org.omg.CORBA.Any bookevent (String customerId, String eventId, String eventtype);
  org.omg.CORBA.Any getbookingSchedule (String customerId);
  org.omg.CORBA.Any dropevent (String customerId, String eventId);
  org.omg.CORBA.Any swapEvent (String customerId, String neweventId, String neweventtype, String oldeventId, String oldeventtype);
} // interface EventSystemInterfaceOperations
