package remoteObject;


/**
* remoteObject/EventSystemInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/TLIN/eclipse-workspace/CORBAa2Lin/EventSystemInterface.idl
* Sunday, July 7, 2019 4:23:46 o'clock PM EDT
*/

public interface EventSystemInterface extends EventSystemInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface EventSystemInterface
