package remoteObject;


/**
* remoteObject/EventSystemInterfacePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/TLIN/eclipse-workspace/CORBAa2Lin/EventSystemInterface.idl
* Sunday, July 7, 2019 4:23:46 o'clock PM EDT
*/

public abstract class EventSystemInterfacePOA extends org.omg.PortableServer.Servant
 implements remoteObject.EventSystemInterfaceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("addEvent", new java.lang.Integer (0));
    _methods.put ("removeEvent", new java.lang.Integer (1));
    _methods.put ("listEventAvailability", new java.lang.Integer (2));
    _methods.put ("bookevent", new java.lang.Integer (3));
    _methods.put ("getbookingSchedule", new java.lang.Integer (4));
    _methods.put ("dropevent", new java.lang.Integer (5));
    _methods.put ("swapEvent", new java.lang.Integer (6));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  /* manager Operations */
       case 0:  // remoteObject/EventSystemInterface/addEvent
       {
         String managerId = in.read_string ();
         String eventId = in.read_string ();
         String eventtype = in.read_string ();
         int capacity = in.read_long ();
         boolean $result = false;
         $result = this.addEvent (managerId, eventId, eventtype, capacity);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // remoteObject/EventSystemInterface/removeEvent
       {
         String managerId = in.read_string ();
         String eventId = in.read_string ();
         String eventtype = in.read_string ();
         boolean $result = false;
         $result = this.removeEvent (managerId, eventId, eventtype);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // remoteObject/EventSystemInterface/listEventAvailability
       {
         String managerId = in.read_string ();
         String eventtype = in.read_string ();
         org.omg.CORBA.Any $result = null;
         $result = this.listEventAvailability (managerId, eventtype);
         out = $rh.createReply();
         out.write_any ($result);
         break;
       }


  /* Customer Operations */
       case 3:  // remoteObject/EventSystemInterface/bookevent
       {
         String customerId = in.read_string ();
         String eventId = in.read_string ();
         String eventtype = in.read_string ();
         org.omg.CORBA.Any $result = null;
         $result = this.bookevent (customerId, eventId, eventtype);
         out = $rh.createReply();
         out.write_any ($result);
         break;
       }

       case 4:  // remoteObject/EventSystemInterface/getbookingSchedule
       {
         String customerId = in.read_string ();
         org.omg.CORBA.Any $result = null;
         $result = this.getbookingSchedule (customerId);
         out = $rh.createReply();
         out.write_any ($result);
         break;
       }

       case 5:  // remoteObject/EventSystemInterface/dropevent
       {
         String customerId = in.read_string ();
         String eventId = in.read_string ();
         org.omg.CORBA.Any $result = null;
         $result = this.dropevent (customerId, eventId);
         out = $rh.createReply();
         out.write_any ($result);
         break;
       }

       case 6:  // remoteObject/EventSystemInterface/swapEvent
       {
         String customerId = in.read_string ();
         String neweventId = in.read_string ();
         String neweventtype = in.read_string ();
         String oldeventId = in.read_string ();
         String oldeventtype = in.read_string ();
         org.omg.CORBA.Any $result = null;
         $result = this.swapEvent (customerId, neweventId, neweventtype, oldeventId, oldeventtype);
         out = $rh.createReply();
         out.write_any ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:remoteObject/EventSystemInterface:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public EventSystemInterface _this() 
  {
    return EventSystemInterfaceHelper.narrow(
    super._this_object());
  }

  public EventSystemInterface _this(org.omg.CORBA.ORB orb) 
  {
    return EventSystemInterfaceHelper.narrow(
    super._this_object(orb));
  }


} // class EventSystemInterfacePOA
